version: '3.8'

services:
  metro-app:
    build: .
    container_name: metro-prediction-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=run_new.py
    volumes:
      # Volume para persistir dados do banco de dados
      - ./data:/app/data
      # Volume para logs (opcional)
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - metro-network

networks:
  metro-network:
    driver: bridge

volumes:
  metro-data:
    driver: local
